name: flutter_ecommerce_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  http: ^1.2.0
  animate_do: ^3.3.4
  app_settings: ^5.1.1
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.2+1
  equatable: ^2.0.5
  fawry_sdk: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_image_slideshow: ^0.1.6
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.5
  geocoding: ^3.0.0
  geolocator: ^11.1.0
  get_it:
  google_fonts: ^6.2.0
  google_maps_flutter: ^2.5.3
  google_sign_in: ^6.2.1
  injectable:
  internet_connection_checker: ^1.0.0+1
  intl: any
  location: ^6.0.2
  pretty_dio_logger: ^1.3.1
  readmore: ^3.0.0
  shared_preferences: ^2.2.3
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3
  flutter_signin_button: ^2.0.0
  flutter_stripe: ^10.1.1
  flutter_dotenv: ^5.1.0


dev_dependencies:
  build_runner:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator:

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - .env
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 900
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200
